### ISSUE TITLE
Default to sql when selecting inmemory network?

### ISSUE THREAD

**Issue by v-stickykeys** [ceramicstudio/wheel#2]
Currently defaults to postgres but would be simpler if it used sql for inmemory or local by default.

**Comment by v-stickykeys** [comment]
<img width="556" alt="image" src="https://user-images.githubusercontent.com/8445610/229207503-2d9d2760-176b-4526-954b-9d0af53d003e.png">

**Comment by dbcfd** [comment]
https://github.com/3box/wheel/pull/3

**Comment by dbcfd** [comment]
Available in v0.1.33 https://github.com/3box/wheel/releases/tag/v0.1.33. @v-stickykeys Can you verify if this is the behavior you want?

**Comment by dbcfd** [comment]
When using InMemory and step through, default is still postgres, causing connection error.

**Comment by dbcfd** [comment]
https://github.com/ceramicstudio/wheel/commit/39b7a61a89d30c48eb83bf8a6160c6047af0d1cf

Available in 0.1.38
